name: Build with Elmstatic

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Build with Elmstatic
      uses: docker://utopianmisfits/elmstatic:latest
      with:
        args: build

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ github.sha }}
        path: _site

