name: github pages

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Elm & Elmstatic
      run: npm i -g elm elmstatic

    - name: Build
      run: elmstatic build

    - name: Create CNAME
      run: echo ${{ secrets.CNAME }} | tee ./_site/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./_site
      with:
        emptyCommits: false
